#!/bin/sh

CRYPT_ID=^luks
FS_ID=/mnt

cd /media/$USER/writable

mkdir -p skel
cp -rv /home/$USER/.config skel/
cp  -v /home/$USER/.bashrc skel/

sudo mkdir -p etc/NetworkManager
sudo cp  -v /etc/hostname                          etc/
sudo cp  -v /etc/hosts                             etc/
sudo cp -rv /etc/luks-keys                         etc/
sudo cp -rv /etc/NetworkManager/system-connections etc/NetworkManager/

mkdir -p crypt
grep $CRYPT_ID /etc/crypttab > crypt/crypttab
grep $FS_ID    /etc/fstab    > crypt/fstab
